id: PD4E29EBE
initial_creation_type: ocr
source_metadata:
  volumes:
    f6db7a15f8024b99b9f0036a8bc316ef:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: ལྷ་མོ་རིགས་བྱེད་མའི་སྒྲུབ་པའི་ཐབས།
      total_pages: 1648
      volume_number: 40
